#define PANTALLABROWSER2 "PANTALLABROWSER2"
#define PANTALLAPREGUNTA "PANTALLAPREGUNTA"
#define PANTALLACONFIRMAR "PANTALLACONFIRMAR"

#define btnAceptarPregunta "btnAceptarPregunta"
#define btnCancelarPregunta "btnCancelarPregunta"
#define btnSiConfirma "btnSiConfirma"
#define btnNoConfirma "btnNoConfirma"
#define btnAceptarPregunta "btnAceptarPregunta"
#define btnCancelarPregunta "btnCancelarPregunta"
#define uiimgFondo "uiimgFondo"
#define uilistadodir "uilistadodir"
#define uivalor "uivalor"
#define uicomboBrowser "uicomboBrowser"
#define uiborde "uiborde"
#define uitextosBox "uitextosBox"
#define uilabelDetalle "uilabelDetalle"